version: "3"

services:
  noetic:
    build:
      context: .
      dockerfile: ./noetic/Dockerfile
    volumes:
      - ./noetic/src:/usr/src/app
    ports:
      - 6080:80
    shm_size: "512m"

  galactic:
    build:
      context: .
      dockerfile: ./galactic/Dockerfile
    volumes:
      - ./galactic/src/:/home/ubuntu/colcon_ws/src
    ports:
      - 6081:80
    shm_size: "512m"
